/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jira;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

/**
 *
 * @author TRINH THE NAM
 */
public class frm_Loading extends javax.swing.JFrame {

    /**
     * Creates new form frm_Loading
     */
    public frm_Loading() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_loadding = new javax.swing.JPanel();
        lbl_backgroung_loadding = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(800, 600, 800, 600));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        pnl_loadding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnl_loadding);
        pnl_loadding.setBounds(0, 0, 0, 0);

        lbl_backgroung_loadding.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        lbl_backgroung_loadding.setFont(new java.awt.Font("UTM Cookies", 0, 36)); // NOI18N
        lbl_backgroung_loadding.setForeground(new java.awt.Color(255, 255, 255));
        lbl_backgroung_loadding.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_backgroung_loadding.setIcon(new javax.swing.ImageIcon("C:\\Users\\TRINH THE NAM\\Desktop\\JW-Còoeee\\JIRA\\JIRA\\src\\icon\\LoadddingTome.gif")); // NOI18N
        lbl_backgroung_loadding.setFocusCycleRoot(true);
        getContentPane().add(lbl_backgroung_loadding);
        lbl_backgroung_loadding.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        frm_Loading Splash = new frm_Loading();
        Splash.setVisible(true);
        DangNhap lognIn = new DangNhap();

        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(25);
                int dem = 0;
                dem = dem + i;
                if (i == 100) {
                    for (int ii = 0; true; ii++) {
                        dem = dem + ii;
                        if (dem == 200) {
                            Splash.dispose();
                            lognIn.setVisible(true);
                            break;
                        }
                    }
                }

            }
        } catch (Exception ex) {
            System.out.println("Lổi Loadding Đăng Nhập");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_backgroung_loadding;
    private javax.swing.JPanel pnl_loadding;
    // End of variables declaration//GEN-END:variables
}
